runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /_ah/mail/log_parsing@ios-logs-email\.appspotmail\.com
  script: main.app

- url: /_ah/mail/.+
  script: bounce_handler.app
  login: admin

- url: /.*
  script: not_found.app
